# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\UserDev\UserPRJ\ABCPhase_LowPowerControlModeule

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\UserDev\UserPRJ\ABCPhase_LowPowerControlModeule

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\UserDev\UserPRJ\ABCPhase_LowPowerControlModeule\CMakeFiles D:\UserDev\UserPRJ\ABCPhase_LowPowerControlModeule\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\UserDev\UserPRJ\ABCPhase_LowPowerControlModeule\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ABCPhase_LowPowerControlModeule

# Build rule for target.
ABCPhase_LowPowerControlModeule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 ABCPhase_LowPowerControlModeule
.PHONY : ABCPhase_LowPowerControlModeule

# fast build rule for target.
ABCPhase_LowPowerControlModeule/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/build
.PHONY : ABCPhase_LowPowerControlModeule/fast

App/app_cmd.obj: App/app_cmd.c.obj
.PHONY : App/app_cmd.obj

# target to build an object file
App/app_cmd.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_cmd.c.obj
.PHONY : App/app_cmd.c.obj

App/app_cmd.i: App/app_cmd.c.i
.PHONY : App/app_cmd.i

# target to preprocess a source file
App/app_cmd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_cmd.c.i
.PHONY : App/app_cmd.c.i

App/app_cmd.s: App/app_cmd.c.s
.PHONY : App/app_cmd.s

# target to generate assembly for a file
App/app_cmd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_cmd.c.s
.PHONY : App/app_cmd.c.s

App/app_lora.obj: App/app_lora.c.obj
.PHONY : App/app_lora.obj

# target to build an object file
App/app_lora.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_lora.c.obj
.PHONY : App/app_lora.c.obj

App/app_lora.i: App/app_lora.c.i
.PHONY : App/app_lora.i

# target to preprocess a source file
App/app_lora.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_lora.c.i
.PHONY : App/app_lora.c.i

App/app_lora.s: App/app_lora.c.s
.PHONY : App/app_lora.s

# target to generate assembly for a file
App/app_lora.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_lora.c.s
.PHONY : App/app_lora.c.s

App/app_main.obj: App/app_main.c.obj
.PHONY : App/app_main.obj

# target to build an object file
App/app_main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_main.c.obj
.PHONY : App/app_main.c.obj

App/app_main.i: App/app_main.c.i
.PHONY : App/app_main.i

# target to preprocess a source file
App/app_main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_main.c.i
.PHONY : App/app_main.c.i

App/app_main.s: App/app_main.c.s
.PHONY : App/app_main.s

# target to generate assembly for a file
App/app_main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/App/app_main.c.s
.PHONY : App/app_main.c.s

Bsp/bsp_dbg_uart.obj: Bsp/bsp_dbg_uart.c.obj
.PHONY : Bsp/bsp_dbg_uart.obj

# target to build an object file
Bsp/bsp_dbg_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_dbg_uart.c.obj
.PHONY : Bsp/bsp_dbg_uart.c.obj

Bsp/bsp_dbg_uart.i: Bsp/bsp_dbg_uart.c.i
.PHONY : Bsp/bsp_dbg_uart.i

# target to preprocess a source file
Bsp/bsp_dbg_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_dbg_uart.c.i
.PHONY : Bsp/bsp_dbg_uart.c.i

Bsp/bsp_dbg_uart.s: Bsp/bsp_dbg_uart.c.s
.PHONY : Bsp/bsp_dbg_uart.s

# target to generate assembly for a file
Bsp/bsp_dbg_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_dbg_uart.c.s
.PHONY : Bsp/bsp_dbg_uart.c.s

Bsp/bsp_gpio.obj: Bsp/bsp_gpio.c.obj
.PHONY : Bsp/bsp_gpio.obj

# target to build an object file
Bsp/bsp_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_gpio.c.obj
.PHONY : Bsp/bsp_gpio.c.obj

Bsp/bsp_gpio.i: Bsp/bsp_gpio.c.i
.PHONY : Bsp/bsp_gpio.i

# target to preprocess a source file
Bsp/bsp_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_gpio.c.i
.PHONY : Bsp/bsp_gpio.c.i

Bsp/bsp_gpio.s: Bsp/bsp_gpio.c.s
.PHONY : Bsp/bsp_gpio.s

# target to generate assembly for a file
Bsp/bsp_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_gpio.c.s
.PHONY : Bsp/bsp_gpio.c.s

Bsp/bsp_lora_uart.obj: Bsp/bsp_lora_uart.c.obj
.PHONY : Bsp/bsp_lora_uart.obj

# target to build an object file
Bsp/bsp_lora_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_lora_uart.c.obj
.PHONY : Bsp/bsp_lora_uart.c.obj

Bsp/bsp_lora_uart.i: Bsp/bsp_lora_uart.c.i
.PHONY : Bsp/bsp_lora_uart.i

# target to preprocess a source file
Bsp/bsp_lora_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_lora_uart.c.i
.PHONY : Bsp/bsp_lora_uart.c.i

Bsp/bsp_lora_uart.s: Bsp/bsp_lora_uart.c.s
.PHONY : Bsp/bsp_lora_uart.s

# target to generate assembly for a file
Bsp/bsp_lora_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_lora_uart.c.s
.PHONY : Bsp/bsp_lora_uart.c.s

Bsp/bsp_system.obj: Bsp/bsp_system.c.obj
.PHONY : Bsp/bsp_system.obj

# target to build an object file
Bsp/bsp_system.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_system.c.obj
.PHONY : Bsp/bsp_system.c.obj

Bsp/bsp_system.i: Bsp/bsp_system.c.i
.PHONY : Bsp/bsp_system.i

# target to preprocess a source file
Bsp/bsp_system.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_system.c.i
.PHONY : Bsp/bsp_system.c.i

Bsp/bsp_system.s: Bsp/bsp_system.c.s
.PHONY : Bsp/bsp_system.s

# target to generate assembly for a file
Bsp/bsp_system.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Bsp/bsp_system.c.s
.PHONY : Bsp/bsp_system.c.s

Core/Src/dma.obj: Core/Src/dma.c.obj
.PHONY : Core/Src/dma.obj

# target to build an object file
Core/Src/dma.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/dma.c.obj
.PHONY : Core/Src/dma.c.obj

Core/Src/dma.i: Core/Src/dma.c.i
.PHONY : Core/Src/dma.i

# target to preprocess a source file
Core/Src/dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/dma.c.i
.PHONY : Core/Src/dma.c.i

Core/Src/dma.s: Core/Src/dma.c.s
.PHONY : Core/Src/dma.s

# target to generate assembly for a file
Core/Src/dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/dma.c.s
.PHONY : Core/Src/dma.c.s

Core/Src/gpio.obj: Core/Src/gpio.c.obj
.PHONY : Core/Src/gpio.obj

# target to build an object file
Core/Src/gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/gpio.c.obj
.PHONY : Core/Src/gpio.c.obj

Core/Src/gpio.i: Core/Src/gpio.c.i
.PHONY : Core/Src/gpio.i

# target to preprocess a source file
Core/Src/gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/gpio.c.i
.PHONY : Core/Src/gpio.c.i

Core/Src/gpio.s: Core/Src/gpio.c.s
.PHONY : Core/Src/gpio.s

# target to generate assembly for a file
Core/Src/gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/gpio.c.s
.PHONY : Core/Src/gpio.c.s

Core/Src/iwdg.obj: Core/Src/iwdg.c.obj
.PHONY : Core/Src/iwdg.obj

# target to build an object file
Core/Src/iwdg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/iwdg.c.obj
.PHONY : Core/Src/iwdg.c.obj

Core/Src/iwdg.i: Core/Src/iwdg.c.i
.PHONY : Core/Src/iwdg.i

# target to preprocess a source file
Core/Src/iwdg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/iwdg.c.i
.PHONY : Core/Src/iwdg.c.i

Core/Src/iwdg.s: Core/Src/iwdg.c.s
.PHONY : Core/Src/iwdg.s

# target to generate assembly for a file
Core/Src/iwdg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/iwdg.c.s
.PHONY : Core/Src/iwdg.c.s

Core/Src/main.obj: Core/Src/main.c.obj
.PHONY : Core/Src/main.obj

# target to build an object file
Core/Src/main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/main.c.obj
.PHONY : Core/Src/main.c.obj

Core/Src/main.i: Core/Src/main.c.i
.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/main.c.i
.PHONY : Core/Src/main.c.i

Core/Src/main.s: Core/Src/main.c.s
.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/main.c.s
.PHONY : Core/Src/main.c.s

Core/Src/stm32l0xx_hal_msp.obj: Core/Src/stm32l0xx_hal_msp.c.obj
.PHONY : Core/Src/stm32l0xx_hal_msp.obj

# target to build an object file
Core/Src/stm32l0xx_hal_msp.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_hal_msp.c.obj
.PHONY : Core/Src/stm32l0xx_hal_msp.c.obj

Core/Src/stm32l0xx_hal_msp.i: Core/Src/stm32l0xx_hal_msp.c.i
.PHONY : Core/Src/stm32l0xx_hal_msp.i

# target to preprocess a source file
Core/Src/stm32l0xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_hal_msp.c.i
.PHONY : Core/Src/stm32l0xx_hal_msp.c.i

Core/Src/stm32l0xx_hal_msp.s: Core/Src/stm32l0xx_hal_msp.c.s
.PHONY : Core/Src/stm32l0xx_hal_msp.s

# target to generate assembly for a file
Core/Src/stm32l0xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_hal_msp.c.s
.PHONY : Core/Src/stm32l0xx_hal_msp.c.s

Core/Src/stm32l0xx_it.obj: Core/Src/stm32l0xx_it.c.obj
.PHONY : Core/Src/stm32l0xx_it.obj

# target to build an object file
Core/Src/stm32l0xx_it.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_it.c.obj
.PHONY : Core/Src/stm32l0xx_it.c.obj

Core/Src/stm32l0xx_it.i: Core/Src/stm32l0xx_it.c.i
.PHONY : Core/Src/stm32l0xx_it.i

# target to preprocess a source file
Core/Src/stm32l0xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_it.c.i
.PHONY : Core/Src/stm32l0xx_it.c.i

Core/Src/stm32l0xx_it.s: Core/Src/stm32l0xx_it.c.s
.PHONY : Core/Src/stm32l0xx_it.s

# target to generate assembly for a file
Core/Src/stm32l0xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/stm32l0xx_it.c.s
.PHONY : Core/Src/stm32l0xx_it.c.s

Core/Src/syscalls.obj: Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.obj

# target to build an object file
Core/Src/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/syscalls.c.obj
.PHONY : Core/Src/syscalls.c.obj

Core/Src/syscalls.i: Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.i

# target to preprocess a source file
Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.c.i

Core/Src/syscalls.s: Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.s

# target to generate assembly for a file
Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.c.s

Core/Src/sysmem.obj: Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.obj

# target to build an object file
Core/Src/sysmem.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/sysmem.c.obj
.PHONY : Core/Src/sysmem.c.obj

Core/Src/sysmem.i: Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.i

# target to preprocess a source file
Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.c.i

Core/Src/sysmem.s: Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.s

# target to generate assembly for a file
Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.c.s

Core/Src/system_stm32l0xx.obj: Core/Src/system_stm32l0xx.c.obj
.PHONY : Core/Src/system_stm32l0xx.obj

# target to build an object file
Core/Src/system_stm32l0xx.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/system_stm32l0xx.c.obj
.PHONY : Core/Src/system_stm32l0xx.c.obj

Core/Src/system_stm32l0xx.i: Core/Src/system_stm32l0xx.c.i
.PHONY : Core/Src/system_stm32l0xx.i

# target to preprocess a source file
Core/Src/system_stm32l0xx.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/system_stm32l0xx.c.i
.PHONY : Core/Src/system_stm32l0xx.c.i

Core/Src/system_stm32l0xx.s: Core/Src/system_stm32l0xx.c.s
.PHONY : Core/Src/system_stm32l0xx.s

# target to generate assembly for a file
Core/Src/system_stm32l0xx.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/system_stm32l0xx.c.s
.PHONY : Core/Src/system_stm32l0xx.c.s

Core/Src/usart.obj: Core/Src/usart.c.obj
.PHONY : Core/Src/usart.obj

# target to build an object file
Core/Src/usart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/usart.c.obj
.PHONY : Core/Src/usart.c.obj

Core/Src/usart.i: Core/Src/usart.c.i
.PHONY : Core/Src/usart.i

# target to preprocess a source file
Core/Src/usart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/usart.c.i
.PHONY : Core/Src/usart.c.i

Core/Src/usart.s: Core/Src/usart.c.s
.PHONY : Core/Src/usart.s

# target to generate assembly for a file
Core/Src/usart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Core/Src/usart.c.s
.PHONY : Core/Src/usart.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c.s

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.obj: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.obj

# target to build an object file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.obj
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.obj

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.i: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.i

# target to preprocess a source file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.i
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.i

Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.s: Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.s

# target to generate assembly for a file
Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.s
.PHONY : Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c.s

startup_stm32l031xx.obj: startup_stm32l031xx.s.obj
.PHONY : startup_stm32l031xx.obj

# target to build an object file
startup_stm32l031xx.s.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\ABCPhase_LowPowerControlModeule.dir\build.make CMakeFiles/ABCPhase_LowPowerControlModeule.dir/startup_stm32l031xx.s.obj
.PHONY : startup_stm32l031xx.s.obj

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... ABCPhase_LowPowerControlModeule
	@echo ... App/app_cmd.obj
	@echo ... App/app_cmd.i
	@echo ... App/app_cmd.s
	@echo ... App/app_lora.obj
	@echo ... App/app_lora.i
	@echo ... App/app_lora.s
	@echo ... App/app_main.obj
	@echo ... App/app_main.i
	@echo ... App/app_main.s
	@echo ... Bsp/bsp_dbg_uart.obj
	@echo ... Bsp/bsp_dbg_uart.i
	@echo ... Bsp/bsp_dbg_uart.s
	@echo ... Bsp/bsp_gpio.obj
	@echo ... Bsp/bsp_gpio.i
	@echo ... Bsp/bsp_gpio.s
	@echo ... Bsp/bsp_lora_uart.obj
	@echo ... Bsp/bsp_lora_uart.i
	@echo ... Bsp/bsp_lora_uart.s
	@echo ... Bsp/bsp_system.obj
	@echo ... Bsp/bsp_system.i
	@echo ... Bsp/bsp_system.s
	@echo ... Core/Src/dma.obj
	@echo ... Core/Src/dma.i
	@echo ... Core/Src/dma.s
	@echo ... Core/Src/gpio.obj
	@echo ... Core/Src/gpio.i
	@echo ... Core/Src/gpio.s
	@echo ... Core/Src/iwdg.obj
	@echo ... Core/Src/iwdg.i
	@echo ... Core/Src/iwdg.s
	@echo ... Core/Src/main.obj
	@echo ... Core/Src/main.i
	@echo ... Core/Src/main.s
	@echo ... Core/Src/stm32l0xx_hal_msp.obj
	@echo ... Core/Src/stm32l0xx_hal_msp.i
	@echo ... Core/Src/stm32l0xx_hal_msp.s
	@echo ... Core/Src/stm32l0xx_it.obj
	@echo ... Core/Src/stm32l0xx_it.i
	@echo ... Core/Src/stm32l0xx_it.s
	@echo ... Core/Src/syscalls.obj
	@echo ... Core/Src/syscalls.i
	@echo ... Core/Src/syscalls.s
	@echo ... Core/Src/sysmem.obj
	@echo ... Core/Src/sysmem.i
	@echo ... Core/Src/sysmem.s
	@echo ... Core/Src/system_stm32l0xx.obj
	@echo ... Core/Src/system_stm32l0xx.i
	@echo ... Core/Src/system_stm32l0xx.s
	@echo ... Core/Src/usart.obj
	@echo ... Core/Src/usart.i
	@echo ... Core/Src/usart.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_exti.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ex.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_flash_ramfunc.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c_ex.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_iwdg.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_lptim.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.s
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.obj
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.i
	@echo ... Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.s
	@echo ... startup_stm32l031xx.obj
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

